### ISSUE TITLE
CQP value is not working in arc gpu

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#1]
I haven't installed the 1.0.0.0 version, but when I tried the 1.0.0.1 version, now the arc gpu can use H264, HEVC, AV1.

Anyway, I removed the json and bak files of the codec to install obs-qsv-onevpl and modified the CQP value.
but it doesn't apply to the actual encoding (this problem is with all QSV encoders)

OBS in vanilla state
= CQP was set to 30, and the log recorded that the value of 23 was set
but the actual CQP encoding proceeded to 30.

02:35:16.627: >>> app not on intel GPU, fall back to old qsv encoder
02:35:16.627: [qsv encoder: 'advanced_video_recording'] settings:
02:35:16.627: 	codec:          AV1
02:35:16.627: 	rate_control:   CQP
02:35:16.627: 	qpi:            23
02:35:16.627: 	qpb:            23
02:35:16.627: 	qpp:            23
02:35:16.627: 	fps_num:        60
02:35:16.627: 	fps_den:        1
02:35:16.627: 	width:          2560
02:35:16.627: 	height:         1440

Log after installing obs-qsv-onevpl.
= I set the CQP to 30, but log recorded as 23 and The actual encoding appears to be CQP=23 
(bitrate was very high in recorded)

02:16:04.670: >>> app not on intel GPU, fall back to old qsv encoder, selected adapter #0
02:16:04.670: Target usage set: Quality
02:16:04.670: [qsv encoder: 'advanced_video_recording'] settings:
02:16:04.670: 	codec:          AV1
02:16:04.670: 	rate_control:   CQP
02:16:04.670: 	qpi:            23
02:16:04.670: 	qpb:            23
02:16:04.670: 	qpp:            23
02:16:04.670: 	fps_num:        60
02:16:04.670: 	fps_den:        1
02:16:04.670: 	width:          2560
02:16:04.670: 	height:         1440
02:16:04.670: [qsv encoder: 'advanced_video_recording'] debug info:
02:16:04.835: 	Implementation:           D3D11
02:16:04.835: 	surf:           D3D11
02:16:04.835: 
02:16:05.007: 	Selected GPU: 0
02:16:05.042: 	NumRefFrame set to: 0
02:16:05.042: 	GopPicSize set to: 120
02:16:05.042: 	GopOptFlag set: CLOSED
02:16:05.042: 	GOPRefDist set to:     4
02:16:05.042: 	VuiNalHrdParameters set: ON
02:16:05.042: 	NalHrdConformance set: ON
02:16:05.042: 	MBBRC set: OFF
02:16:05.042: 	BPyramid set: ON
02:16:05.042: 	Trellis set: AUTO
02:16:05.042: 	PRef set: Simple
02:16:05.042: 	MotionVectorsOverPicBoundaries set: AUTO
02:16:05.042: 	WeightedPred set: ON
02:16:05.042: 	WeightedBiPred set: ON
02:16:05.042: Feature extended buffer size: 7
02:16:05.060: 	Surface count:     112
02:16:05.063: Video params extended buffer size: 1
02:16:05.063: 	TaskPool count:    4
02:16:05.063: 	major:          2
02:16:05.063: 	minor:          8

**Comment by ma3uk** [comment]
Fixed in release 1.0.0.2

**Comment by ckdt1105** [comment]
> Fixed in release 1.0.0.2

CQP now works normally on ARC GPU
Thank you

15:45:13.881: >>> app not on intel GPU, fall back to old qsv encoder, selected adapter #0
15:45:13.881: Target usage set: Quality
15:45:13.881: [qsv encoder: 'advanced_video_recording'] settings:
15:45:13.881: 	codec:          AV1
15:45:13.881: 	rate_control:   CQP
15:45:13.881: 	CQP:            160

15:48:16.433: >>> app not on intel GPU, fall back to old qsv encoder, selected adapter #0
15:48:16.433: Target usage set: Balanced
15:48:16.433: [qsv encoder: 'advanced_video_recording'] settings:
15:48:16.433: 	codec:          HEVC
15:48:16.433: 	rate_control:   CQP
15:48:16.433: 	CQP:            40

15:57:43.899: >>> app not on intel GPU, fall back to old qsv encoder, selected adapter #0
15:57:43.899: Target usage set: Balanced
15:57:43.899: [qsv encoder: 'advanced_video_recording'] settings:
15:57:43.899: 	codec:          H.264
15:57:43.899: 	rate_control:   CQP
15:57:43.899: 	CQP:            40
