### ISSUE TITLE
lookahead options

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#15]
version : 1.1.0.0_dev5

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/97d55b16-0ed9-420a-b304-fbfc441abf6b)

Options related to lookahead can only be activated in CBR and VBR.
Is it partially disabled because it is difficult to implement in its current state?

![스크린샷 2023-08-30 190139](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/afd16125-7573-47c4-ae72-5521df004e8e)
And the LA_EXT_ICQ option seems to be broken.

**Comment by ckdt1105** [comment]
After activating the lookahead option in CBR or VBR
then return to the ICQ or CQP option, 
the lookahead option that disappeared will be returned.
I think this is a bug.

**Comment by ma3uk** [comment]
Fixed in dev6 build
