### ISSUE TITLE
1.1.0.0_ In the dev5 version, there is a problem with the progress bar dragging and stuttering during playback of videos recorded with HEVC encoding

### ISSUE THREAD

**Issue by ouco1986** [ma3uk/obs-qsv-onevpl#16]
Thank you to the author for providing such a great plugin. I am using the latest 1.1.0.0_ In the dev5 version, it was found that pulling the progress bar during playback of videos recorded with HEVC would cause lag, and other encoders were fine. Suspect that there is an issue with the gopoptflag setting in HEVC. This setting is available in the dev4 version, but it was not found in the dev5 version. Additionally, it seems that the encoding scheme for live streaming cannot be chosen for recording, as this will only result in live streaming and not recording. I hope the author can provide a solution. Thank you. Since I am using a translation software to post, if the description is unclear

**Comment by ma3uk** [comment]
Try dev6 build

**Comment by ouco1986** [comment]
> Try experimental build

Thank you very much. Using the experiential_ 1,Both of the issues I mentioned have been resolved. This version of the encoder has high efficiency. Great
