### ISSUE TITLE
LA_cbr does not limit bitrate

### ISSUE THREAD

**Issue by UsatoTokari** [ma3uk/obs-qsv-onevpl#19]
I am encountering problems with encoding using LA_сbr and the problem depends on the tab used in OBS. When selecting encoding options in the streaming tab, and then selecting the "use stream encoder" entry in the tab, I get the bitrate limit I need, however, the adaptive b-frame function does not work properly and I get the same number of b-frames for each miniGOP (I select 7 ).
![2023-10-18 211855](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/45bff0ef-71ab-4f3e-8ce4-43eaf08583cd)

 In the second option, I select encoding parameters in the recording tab and with the same configuration of parameters, adaptive b-frames work properly, but the bitrate limitation does not work. When I select bitrate=6000Kbps, I get video with a bitrate of 100Mb/s or more.

![2023-10-18 211951](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/56692987-a301-4384-ac58-b69ee3c28e2d)

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/5e5f1a02-ff03-46eb-9e58-64cb23a5959e)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/43b6583f-e975-489c-ad2f-5c2389273faa)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/ba1baf69-68ea-49a2-96c5-8b83816d6ce6)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/13e6d940-6fe1-49f3-a32c-37bb165f2668)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/276fe4f4-883f-42f8-99b9-02ec3a7c3f2d)
I use the same encoder settings for both options. And I selected it for the purpose of using Enctools, using the triggers described here
https://github.com/intel/media-delivery/blob/master/doc/quality.rst#h-264-bitstream-quality-measure-example

CPU: 11700 with Uhd 750
Driver: 31.0.101.4887
OBS 29.1.3
obs-qsv-onevpl 1.1.0.0_dev6

**Comment by ma3uk** [comment]
According to the screenshots you provided, you are using an outdated version of the plugin. In version 1.1.0.0_dev6, LA_CBR is no longer available. Update the plugin version in the plugins folder and clear the encoder configuration.

**Comment by UsatoTokari** [comment]
Yes, you were right. I was sure that I updated the plugin, but instead of the specified directory in the readme, I probably copied the plugin file to another one. Thank you for your help.
