### ISSUE TITLE
CBR bitrate can't change after encoding start

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#2]
basic info: OBS 29.1.1, intel Arc A380
In vanilla OBS, it was possible to change the bitrate in CBR mode during encoding.
However, this is not possible with version 1.0.0.2 of the plugin.

**Comment by ma3uk** [comment]
The method that was used in the Media SDK (Vanilla OBS QSV) does not work with OneVPL and causes errors. The functionality will be added in subsequent releases, but this is not a priority.

**Comment by ckdt1105** [comment]
> The method that was used in the Media SDK (Vanilla OBS QSV) does not work with OneVPL and causes errors. The functionality will be added in subsequent releases, but this is not a priority.

I sometimes used this function without thinking when the YouTube live streaming server was unstable, but it is harder to implement in onevpl than I thought.

**Comment by ma3uk** [comment]
Added in 1.1.0.0_dev pre-release.
