### ISSUE TITLE
obs-qsv-test.exe not available?

### ISSUE THREAD

**Issue by Rocky712YT** [ma3uk/obs-qsv-onevpl#20]
Hi, this isn´t specifically an issue, but the "How to install"-guide says you have to place the obs-qsv-test.exe into the correct folder.
I looked through the files and I simply couldn´t find them. Did I miss something?

**Comment by ma3uk** [comment]
The latest versions of OBS Studio come with a fixed file obs-qsv-test.exe , its replacement is no longer required. In future releases, the mention of the replacement will be removed.
