### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by BrycensRanch** [ma3uk/obs-qsv-onevpl#21]
As OneVPL is new, why not give performance benchmarks for future users and current to understand the benefits of OneVPL  - I can't tell the difference

**Comment by BrycensRanch** [comment]
Nevermind, the module failed to load - that seemed to be the issue.

**Comment by ma3uk** [comment]
Are there any problems with running the plugin? If there is, then tell us in more detail on which system you are running and what steps have been performed.
