### ISSUE TITLE
Hardware device returned unexpected errors (MFX_ERR_DEVICE_FAILED)

### ISSUE THREAD

**Issue by UsatoTokari** [ma3uk/obs-qsv-onevpl#22]
I get an error when I try to recording using onevpl_H264 (also with HEVC and vp9)
![SC_err](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/32e739f6-aaaa-4591-b233-151bc7367cf0)
I've tried different encoder options, turning off Enctools, Lookahed, and Extbrc, but I always get an error. At the moment I am using driver 4885, but I have tested everything up to 4952. I also tried installing all versions of OBS from 30beta to 30RC2. When using obs 29.1.3, the log file says that the onevpl module is not loaded (or is not supported for the version. I can accurately reproduce this if necessary), so I decided (maybe I’m wrong) that build dev6 is intended for obs 30+, because it doesn’t I can use it with 29.1.3
As a result, I can record with oneVPL dev5 in obs 29.1.3 and 30RK2, but the dev6 version in obs 30+ gives an error and the module does not load in 29.1.3.

My log [2023-11-10 20-09-24.txt](https://github.com/ma3uk/obs-qsv-onevpl/files/13321858/2023-11-10.20-09-24.txt)

**Comment by ma3uk** [comment]
@UsatoTokari Is Intel integrated graphics used? Because I don't see Arc family graphics in the log file. In order to exclude possible errors, please enable the Lowpower parameter. If there will be no more errors after enabling it, be sure to report here

I inform you in advance that in the next versions of the plugin there will be a refusal to support the encoding mode without enabling Lowpower, since Intel refuses to support it further.

**Comment by UsatoTokari** [comment]
I use Intel integrated graphics, in my case it's UHD 750. I tried using forced LowPower, but it didn't help.
[2023-11-11 17-03-04.txt](https://github.com/ma3uk/obs-qsv-onevpl/files/13325765/2023-11-11.17-03-04.txt)

![CS1](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/242f4637-3bc6-4955-b9d5-4da41fc14b73)
![cs2](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/58f542f4-113a-4113-9c4f-824f5dced5ae)
![cs3](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/438c967c-b02d-49f4-8407-c129f7acb643)
Perhaps I should force settings that are not compatible with lowpower, but I have a lack of knowledge about this.

**Comment by ma3uk** [comment]
[obs-qsvonevpl.zip](https://github.com/ma3uk/obs-qsv-onevpl/files/13325797/obs-qsvonevpl.zip)
@UsatoTokari  Try this build

**Comment by UsatoTokari** [comment]
still throws an error.
![cs4](https://github.com/ma3uk/obs-qsv-onevpl/assets/148376468/e11059a4-cdfb-487c-86cf-0d13719ba538)
[2023-11-11 22-15-08.txt](https://github.com/ma3uk/obs-qsv-onevpl/files/13326310/2023-11-11.22-15-08.txt)

**Comment by ma3uk** [comment]
@UsatoTokari  Contact me at Discord "myonezgg", we will solve the problem.

**Comment by ALETTERR** [comment]
I encountered the same problem
