### ISSUE TITLE
Intel ARC A380 AV1 performance drop with newer drivers

### ISSUE THREAD

**Issue by werdwerdus** [ma3uk/obs-qsv-onevpl#23]
I have noticed both in OBS as well as Davinci Resolve that updating to the 4885 and newer drivers has caused a reduction in AV1 encoding performance of almost 90%. I am now getting dropped frames due to encoder lag occasionally in OBS (up to about 0.5% or so encoding 2048x1152@60fps, whereas before I never dropped any frames even encoding up to 3000x1920@60fps). And using Davinci Resolve during project export/encode, the encoding speed has dropped from about 5-10x realtime down to about 0.5-1.0x realtime.

I tried the most recent WHQL driver 4887 as well as the WHQL 4953 driver with nearly identical results. If I downgrade back to the previous driver 4369 the performance comes back up.

Any ideas? I am on Windows 10 Pro 22H2, AMD Ryzen 7 3800X, Nvidia RTX 3070, and Intel ARC A380

**Comment by werdwerdus** [comment]
I did try using the "Display Driver Uninstaller" / DDU and did not notice any change in behavior.

**Comment by ma3uk** [comment]
Greetings! Unfortunately I can't help with driver related issues, you should make an Issue in the repository [https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT) This repository is an official communication for communication with the community.
For my part, I can say that most likely a new driver with oneVPL 2.10 support will be released in the near future, at least today there was an official release of VPL 2.10 in which there will be many fixes and improvements.
Please, to satisfy my interest, after the release of a new version of the driver, let me know about the changes it has brought for you.

**Comment by werdwerdus** [comment]
Hi, I did do some more research and found out the "resizable BAR" may have been the issue. I went through all the steps necessary to get it enabled on my system and it seems to have resolved the issue. Sorry to waste your time!
