### ISSUE TITLE
Coding error during live broadcast

### ISSUE THREAD

**Issue by DDXDB** [ma3uk/obs-qsv-onevpl#28]
I was broadcasting live with OneVPL HEVC and there was a coding break and no error popup.
No response when OBS is closed.
QSV HEVC with OBS is no problem.
log file:
[2024-05-16 02-05-47.txt](https://github.com/ma3uk/obs-qsv-onevpl/files/15326108/2024-05-16.02-05-47.txt)

**Comment by ma3uk** [comment]
@DDXDB Did the error occur about 10 minutes after the broadcast started?

**Comment by ma3uk** [comment]
@DDXDB Update the plugin to version 1.2.0.3, it has been modified to fix this error with driver 5518

**Comment by DDXDB** [comment]
I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.

**Comment by ma3uk** [comment]
> I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.

I don't quite understand, are there any problems with version 0.6 again? Please clarify

**Comment by DDXDB** [comment]
> > I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.
> 
> I don't quite understand, are there any problems with version 0.6 again? Please clarify

When I started live streaming with oneVpl qsv 10 minutes later I started losing frames badly, but the log file didn't seem to report errors. When I used the qsv encoder that came with obs, it worked fine.

**Comment by ma3uk** [comment]
> > > I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.
> > 
> > 
> > I don't quite understand, are there any problems with version 0.6 again? Please clarify
> 
> When I started live streaming with oneVpl qsv 10 minutes later I started losing frames badly, but the log file didn't seem to report errors. When I used the qsv encoder that came with obs, it worked fine.

Send the parameters with which the broadcast was started

**Comment by DDXDB** [comment]
> > > > I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.
> > > 
> > > 
> > > I don't quite understand, are there any problems with version 0.6 again? Please clarify
> > 
> > 
> > When I started live streaming with oneVpl qsv 10 minutes later I started losing frames badly, but the log file didn't seem to report errors. When I used the qsv encoder that came with obs, it worked fine.
> 
> Send the parameters with which the broadcast was started

[2024-08-21 23-41-59.txt](https://github.com/user-attachments/files/16694894/2024-08-21.23-41-59.txt)
I take it back. This is the log I just got. There are many errors.

**Comment by ma3uk** [comment]
> > > > > I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.
> > > > 
> > > > 
> > > > I don't quite understand, are there any problems with version 0.6 again? Please clarify
> > > 
> > > 
> > > When I started live streaming with oneVpl qsv 10 minutes later I started losing frames badly, but the log file didn't seem to report errors. When I used the qsv encoder that came with obs, it worked fine.
> > 
> > 
> > Send the parameters with which the broadcast was started
> 
> [2024-08-21 23-41-59.txt](https://github.com/user-attachments/files/16694894/2024-08-21.23-41-59.txt) I take it back. This is the log I just got. There are many errors.

Please try version 1.2.0.7. I found a bug related to the HEVC codec. Maybe this will help with your problem.
If you used fractional fps (59.94), then it will help 100%

**Comment by DDXDB** [comment]
> > > > > > I'm not sure if version 0.6 had a similar issue, with severe frame loss after 10 minutes of live streaming, but the obs display was fine and the log file was not abnormal.
> > > > > 
> > > > > 
> > > > > I don't quite understand, are there any problems with version 0.6 again? Please clarify
> > > > 
> > > > 
> > > > When I started live streaming with oneVpl qsv 10 minutes later I started losing frames badly, but the log file didn't seem to report errors. When I used the qsv encoder that came with obs, it worked fine.
> > > 
> > > 
> > > Send the parameters with which the broadcast was started
> > 
> > 
> > [2024-08-21 23-41-59.txt](https://github.com/user-attachments/files/16694894/2024-08-21.23-41-59.txt) I take it back. This is the log I just got. There are many errors.
> 
> Please try version 1.2.0.7. I found a bug related to the HEVC codec. Maybe this will help with your problem. If you used fractional fps (59.94), then it will help 100%

It looks like the problem has been fixed and I did not repeat the previous error in 5 hours of testing. I'll keep testing.
