### ISSUE TITLE
HEVC GPB default OFF for better seek performance

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#3]
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/afe24fcd-ffae-461e-9f2a-042e1eedb92b)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/7c6409bd-e714-4755-8878-abc801e2f1b6)
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/9903f385-de1c-4043-a1eb-4714802b4e21)
(The description is a regular P-frame, but in reality regular B-frames are used)

Since this option is basically ON, it is inconvenient to move in units of key frames when searching for the previous frame.

The QSV AV1 had similar inconveniences, so I looked for options for it, but I couldn't.

**Comment by ma3uk** [comment]
The default state will be changed to AUTO in the next release.
