### ISSUE TITLE
hang if 59.94fps selected

### ISSUE THREAD

**Issue by veritronx** [ma3uk/obs-qsv-onevpl#31]
obs hangs when trying to record using this plugin at 2560x1440 with fps set to 59.94 on an arc a310 using any of the plugin's codecs

plugin version 1.2.0.5
driver version 5971
obs version 30.2.2 and 30.2.3

happens even on clean obs install with no sources, locks up while trying to start a recording, doesn't lock up when fps is changed to 60

**Comment by ma3uk** [comment]
@veritronx Fixed in 1.2.0.6 build
