### ISSUE TITLE
drive 32.101.6127 Encoding overloaded

### ISSUE THREAD

**Issue by DDXDB** [ma3uk/obs-qsv-onevpl#32]
use：[1.2.0.7_dev](https://github.com/ma3uk/obs-qsv-onevpl/releases/tag/1.2.0.7_dev)

**Comment by ma3uk** [comment]
Provide more information, which codec, which video settings, which encoding settings are set.

**Comment by DDXDB** [comment]
Sorry, I couldn't reproduce the error, and Intel repeatedly pushed me the 6127 driver, which seems to have been corrected.

**Comment by ma3uk** [comment]
> Sorry, I couldn't reproduce the error, and Intel repeatedly pushed me the 6127 driver, which seems to have been corrected.

Please check the stability of the 6127 and 6129 drivers.
On my machine, I ran into the problem of skipping frames, without displaying them in statistics, if you encounter a similar problem, at the moment there is only one solution - returning to the driver with a version up to 6083.

**Comment by DDXDB** [comment]
[2024-10-27 08-30-39.txt](https://github.com/user-attachments/files/17532408/2024-10-27.08-30-39.txt)
The error was repeated. Occurs when HDR is encoded

**Comment by ma3uk** [comment]
Have you upgraded to version 1.2.0.8?
