### ISSUE TITLE
With driver 6332, using UHD770 integrated graphics alongside an A770 discrete card makes the plugin ineffective.(在6332驱动下使用UHD770核显搭配a770独显安装插件后无效 翻译成英文)

### ISSUE THREAD

**Issue by what2008** [ma3uk/obs-qsv-onevpl#33]
Using driver 6332 with UHD770 integrated graphics and an A770 discrete card, after placing obs-qsvonevpl.dll in obs-studio\bin\64bit, the three QSVONE options do not appear in the encoder selection interface.
使用的驱动是6332,显卡分别是UHD770核显与a770独显,将obs-qsvonevpl.dll文件放入obs-studio\bin\64bit后编码器选择界面并没有出现qsvone的那三个选项
![16cc3e68b1855a89aad58d8efcce5b0](https://github.com/user-attachments/assets/8fc04b1e-11d3-48a0-846b-bc316c10bb43)

**Comment by ma3uk** [comment]
Have you solved the problem?
