### ISSUE TITLE
Too large buffer size for OBS

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#5]
In CBR mode, when switching from a static scene to a dynamic scene
the bitrate spikes and then maintains a level higher than the target bitrate for a while
then gradually moves towards the target level

In OBS in vanilla, there was a bitrate spike but quickly headed towards the target bitrate

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/d1b26f79-15c5-4c45-b96a-8746bc15d3eb)
https://www.intel.com/content/dam/develop/external/us/en/documents/intel-media-developers-guide.pdf
![화면 캡처 2023-05-25 012640](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/125d082f-3eea-422f-a41b-9f89f178bd9b)
https://www.intel.com/content/www/us/en/developer/articles/technical/common-bitrate-control-methods-in-intel-media-sdk.html

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/eff5fc5b-b2eb-4cca-b51b-f45da8b4dc8b)
(obs-qsv-onevpl 1.1.0.0_dev)

I was able to make it behave like 'strict CBR' by setting the buffer size to 1Kb when the target bitrate is 10000Kbps
(I don't know why 1Kb works and I don't know what value is the optimal value, but it works anyway)
And from the buffer size between 80 and 90Kb, bitrate spikes and excessive bitrates occur

Considering that OBS is basically a streaming program, I think the buffer size should be set very small by default.

**Comment by ckdt1105** [comment]
@ma3uk 
https://drive.google.com/drive/folders/17GW68tEnmyT8kW4BnmWG-_6x4IBO0KqJ?usp=sharing
This is a recorded video where you can see the difference.
Target bitrates are all set to 10000 Kbps
If the buffer size is auto, it will cause network problems on services like YouTube and Twitch.

**Comment by ma3uk** [comment]
@ckdt1105 In build 1.1.0.0_dev2, the default value has been changed to TargetBitrate/8. The value is selected experimentally, the value below may cause flickering.
