### ISSUE TITLE
AV1 youtube green bar :p

### ISSUE THREAD

**Issue by guraking** [ma3uk/obs-qsv-onevpl#7]
https://www.youtube.com/watch?v=zYeB8OYw99I

bottom green bar lol i know beta ver check plz :]

**Comment by ma3uk** [comment]
@guraking Please provide a list of settings with which the green bar appears.

**Comment by ma3uk** [comment]
I checked, there really is a problem, at the moment the only solution is to set GopRefDist to position 1. Perhaps this is a transcoding problem on the part of Youtube, because there are no problems on the local recording, but I will try to solve it from my side.

**Comment by ma3uk** [comment]
@guraking Fixed in release 1.1.0.0_dev3
