### ISSUE TITLE
i'm real time stream 1 hour test but youtube time video jump

### ISSUE THREAD

**Issue by guraking** [ma3uk/obs-qsv-onevpl#8]
If you look at this time video jump 

I don't know exactly why

https://youtu.be/LkAfgOyGn94?t=1847

**Comment by guraking** [comment]
my setting 

https://youtu.be/LkAfgOyGn94?t=3217

**Comment by ckdt1105** [comment]
@guraking 
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/28d792d8-594a-49e5-9660-2810e98395ad)
이 주제하고 관련 없는 이야기긴 한데 유튜브에 70000 kbps로 쏘면 obs에서는 5000 kbps 정도로 낮춰서 송출 합니다.
It's a unrelated to this topic, if you broadcasting 70000 kbps at YouTube, OBS will be lowered to 5000 kbps

안정적인 비트레이트는 10000kbps 정도이며 15000 ~ 20000kbps 정도 되면 네트워크 전송 손실이 생깁니다.
A stable bitrate is around 10000 kbps, and network transmission loss occurs around 15000 - 20000 kbps.

**Comment by guraking** [comment]
@ckdt1105 한국분이신가보군요 적으신 글 내용을 다 알고 있습니다 ^^ 네 4k로 유튜브 권장사항 4k기준 7만에서 15만까지 세팅이라 av1 압축률을 이용해서 최소 권장사항으로 출력을 보냈급니다. 여기 플러그인을 안쓰고 문제없이 잘 작동하였습니다

**Comment by ckdt1105** [comment]
> @ckdt1105 한국분이신가보군요 적으신 글 내용을 다 알고 있습니다 ^^ 네 4k로 유튜브 권장사항 4k기준 2160p (4K) 66–85 Mbps 세팅이라 av1 압축률을 이용해서 권장사항 기준으로 출력을 보냈급니다. 여기 플러그인을 안쓰고 문제없이 잘 작동하였습니다. (제가 올린 나머지 영상들은 전혀 문제 없이 잘녹화 되었습니다 참고햐보시면 될꺼같네요 obs 기본 av1 으로 아무 문제가 없었습니다)
> 
> 권장사항을 다시보니 5만까지 낮춰도 문제없을꺼같네요 ^^
> 
> 아참 전 케이티 인터넷 쓰고있습니다. 그리고 참고로 저는 트위치를 메인으로 하고 유튜브를 녹화용으로 쓰고있습니다. 그래서 로컬은 따로하지 않아서 모르겠습니다.
> 
> 1080p 로 보내고 유튜브에서 그냥 4k로 저장시켰습니다. 출력배율 조정은 쓰지않았습니다
> 
> 유튜브 권장 스트림 참고용 https://support.google.com/youtube/answer/1722171?hl=en#zippy=%2Cbitrate

일단 업로드와 라이브는 권장사항이 다릅니다
First of all, upload and live have different recommendations.
https://support.google.com/youtube/answer/2853702?hl=en#zippy=%2Ck-p-fps

또한 onvpl 플러그인을 쓰지 않아도 QSV 인코더에서는 65535kbps 이상으로 설정하면 오버플로우가 일어납니다.
(65535kbps까지는 정상적으로 송출 되지만 70000kbps로 송출 시 (70000-65535)kbps로 송출 됩니다)
Also, even if you don't use the onvpl plugin, overflow occurs when you set it to 65535 kbps or higher in the QSV encoder.

저도 똑같이 A380 그래픽카드를 사용 하고 있으니 동일한 현상이 생길 것 같습니다.
I'm using the same A380 graphics card, so the same thing seems to happen.

그리고 로컬 녹화본이 없다고 하시니 구간 스킵이 유튜브 문제인지 QSV 문제인지 확실하지는 않아 보입니다.
And since you say there is no local recording, it seems unclear whether the section skip is a YouTube problem or a QSV problem.

만약 네트워크 손실로 인해 유튜브 서버에 영상이 제대로 전송 되지 않았다면 구간이 스킵 된 것 처럼 영상에 남아 있을 가능성이 있습니다.
If the video was not properly transmitted to the YouTube server due to network loss, there is a possibility that the section will remain in the video as if it were skipped.

**Comment by guraking** [comment]
@ckdt1105 
손실된 프레임은 아주 미세하게 일어나고 그외에는 손실이 없었습니다. 항상 체크를 하고있거든요

**Comment by ckdt1105** [comment]
@guraking 

> @ckdt1105 손실된 프레임은 아주 미세하게 일어나고 그 외에는 손실이 없었습니다. 항상 체크를 하고 있거든요 그리고 알려주신데로 비트레이트를 내리고 다시 녹화해보겠습니다

그렇군요 그러면 큰 구간의 스킵은 네트워크로 인해 발생하지 않았다는 거네요
It means, skipping segment was not caused by the network.

onvpl을 사용한 유튜브 라이브 녹화본이 있지만 이걸 다 확인하기에는 무리가 있으니 이러한 현상이 일어나는지 모니터링 해 보겠습니다.
I have a YouTube live recording using onvpl, but it's difficult to check all of this, so I'll monitor whether this happens.
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/182b770a-7467-43cf-a8a7-dd0b918a3d9e)

**Comment by ma3uk** [comment]
@guraking As mentioned above, Youtube does not assume live broadcasts with such a high bitrate.
The oneVPL library and MSDK have a limit on the values used for the bitrate and for the buffer size, for example, for the bitrate - these are internal library restrictions that I cannot influence. One of these restrictions is the use of 16 bits of type for the parameters used for installation, the limit of which is just the value of 65536 bytes, which causes an overflow. For bitrate values exceeding 65536, it is assumed to use CQP or ICQ modes.
I will try to contact Intel to find out if it is possible to expand variables to a 32-bit value.

**Comment by ma3uk** [comment]
@guraking Regarding your video settings, I recommend using the GopRefDist value for the AV1 codec at least 8, ideally 16 - this will greatly improve compression, but it will not affect the quality, and in heavy scenes it will stabilize the video quality. Also include MBBRC and RDA, this will improve the psychovisual perception of video even with a reduced bitrate.

**Comment by guraking** [comment]
> @guraking Regarding your video settings, I recommend using the GopRefDist value for the AV1 codec at least 8, ideally 16 - this will greatly improve compression, but it will not affect the quality, and in heavy scenes it will stabilize the video quality. Also include MBBRC and RDA, this will improve the psychovisual perception of video even with a reduced bitrate.

@ma3uk 

ok thx bro

2 hour long time no problem (60000 fixed)

maybe high bitrate issu thx advice bro

**Comment by ma3uk** [comment]
@guraking I posted a Dev4 build with a bypass of the 65536 limit, please try it.

**Comment by ckdt1105** [comment]
@guraking 

아 그렇군요 여러가지 테스트를 해보셨군요, 고생이 많으십니다.

직접 해보셔서 알겠지만 인텔 arc의 AV1 품질은 엔비디아 20번대의 HEVC보다 못 합니다.
![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/96421dff-39f8-4f52-9a88-3156b0ca0e52)

그리고 보조 GPU로 OBS 인코딩에 사용 했을 때는
메인GPU의 부담을 줄여 주어서 GPU의 병목이 걸리는 게임은 프레임 향상의 효과가 있지만
CPU의 병목이 주로 생기는 경쟁형 게임 같은 경우에는 오히려 게임 프레임이 떨어집니다.
예시)리그오브레전드, 오버워치2, APEX, 디비전2, 발로란트 등....

이는 보조 GPU로 인코딩 시 OBS화면을 무압축으로 RAM에 저장 한 다음 보조 GPU의 VRAM으로 복사 해온 뒤 인코딩을 하기 때문에 RAM 레이턴시가 늘어지기 때문에 그렇습니다.

아래 글은 제가 오늘 작성한 A380 후기 입니다, 참고가 되셨으면 좋겠네요
https://tgd.kr/g/tip/70357149

**Comment by guraking** [comment]
> @guraking
> 
> 아 그렇군요 여러가지 테스트를 해보셨군요, 고생이 많으십니다.
> 
> 직접 해보셔서 알겠지만 인텔 arc의 AV1 품질은 엔비디아 20번대의 HEVC보다 못합니다. https://quasarzone.com/bbs/qn_hardware/views/1469834 ![image](https://user-images.githubusercontent.com/74068143/242670557-96421dff-39f8-4f52-9a88-3156b0ca0e52.png)
> 
> 그리고 보조 GPU로 OBS 인코딩에 사용 했을 때는 메인GPU의 부담을 줄여 주어서 GPU의 병목이 걸리는 게임은 프레임 향상의 효과가 있지만 CPU의 병목이 주로 생기는 경쟁형 게임 같은 경우에는 오히려 게임 프레임이 떨어집니다. 예시)리그오브레전드, 오버워치2, APEX 레전드, 디비전2, 발로란트 등....
> 
> 이는 보조 GPU로 인코딩 시 OBS화면을 무압축으로 RAM에 저장 한 다음 보조 GPU의 VRAM으로 복사 해온 뒤 인코딩을 하기 때문에 RAM 레이턴시가 늘어지기 때문에 그렇습니다.
> 
> 아래 글은 제가 오늘 작성한 A380 후기 입니다, 참고가 되셨으면 좋겠네요 https://tgd.kr/g/tip/70357149

저는 그래서 그 병목 현상을 없애기 위해서 7800x3d cpu 를 선탹했습니다 v캐쉬를 이용한 램과 cpu 그 간섭을 안받을려고 그래서 최근에 나온 암드 7800x3d로 간 이유가 되겠네요 이글은 예전에도 저 트게더 글은 예전에도 한번 쓰신적이 있으셨던걸로 기억합니다 저보다 더 빠르게 a380을 사셔서 테스트 하셔서 트게더에 굴을 남기신걸 본적이 있는거같습니다 이런분을 뵈다니 영광이네요 ㅎㅎㅎ

**Comment by guraking** [comment]
@ckdt1105 

~ 직접 해보셔서 알겠지만 인텔 arc의 AV1 품질은 엔비디아 20번대의 HEVC보다 못합니다. ~
^^ 알고있습니다.

이 링크가 방금 제 동생하고 4080 av1을 테스트한 영상입니다.
제 영상과 이 동생 영상과 비교해보면 화질차이는 엔비디아 압승인게 맞습니다.
제 데탑은 a380과 4080을 같이 쓰고 있어서 두가지를 다 테스트 가능합니다. 
확실히 엔비디아 압승이 맞습니다....AV1 기준

https://www.youtube.com/watch?v=kkrquza8MkM

**Comment by ckdt1105** [comment]
@guraking 
그런데 어디에서 글을 보고 한국인이 A380을 샀을까 의문 이었는데
제가 쓴 글을 보고 샀던 것일 줄은 몰랐네요 ㅎㅎ;;
아무튼 감사합니다

**Comment by guraking** [comment]
> 



> @guraking 그런데 어디에서 글을 보고 한국인이 A380을 샀을까 의문 이었는데 제가 쓴 글을 보고 샀던 것일 줄은 몰랐네요 ㅎㅎ;; 아무튼 감사합니다.

아닙니다. 제가 더 ㅎㅎ 감사합니다. 
그 트게더 글을 보지 않았다면 A380은 생각도 안했을꺼 같네요 ㅎㅎ

**Comment by guraking** [comment]
close

**Comment by ckdt1105** [comment]
> @guraking Regarding your video settings, I recommend using the GopRefDist value for the AV1 codec at least 8, ideally 16 - this will greatly improve compression, but it will not affect the quality, and in heavy scenes it will stabilize the video quality. Also include MBBRC and RDO, this will improve the psychovisual perception of video even with a reduced bitrate.

I also got the best compression ratio with a GOP value of 8 or 16.
thank you

![AV1GOP](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/afa6d384-8dfd-4e46-bf24-b0c299138c17)

**Comment by guraking** [comment]
I checked it out
many encoder change so obs bug..
qsv av1, qsv-onevpl av1 changing it
maybe obs bug.... i'm checked

**Comment by guraking** [comment]
@ma3uk @ckdt1105 

원인을 찾아보니 제 랜카드가 킬온 스위치가 작동이 되어버리네요 그래서 그부분을 찾아서 제거해주니
방송이 재접속 하는 문제가 해결되었습니다. 혹시나 참고 하시길 바래요

ok i checked my lan card kill - _ - so youtube re connect 
my bug close issu

**Comment by ma3uk** [comment]
> @ma3uk
> 
> > @guraking Regarding your video settings, I recommend using the GopRefDist value for the AV1 codec at least 8, ideally 16 - this will greatly improve compression, but it will not affect the quality, and in heavy scenes it will stabilize the video quality. Also include MBBRC and RDO, this will improve the psychovisual perception of video even with a reduced bitrate.
> 
> I also got the best compression ratio with a GOP value of 8 or 16 and MBBRC, RDO is auto or on thank you
> 
> ![AV1GOP](https://user-images.githubusercontent.com/74068143/242868123-afa6d384-8dfd-4e46-bf24-b0c299138c17.png) ![mbbrc,rdo](https://user-images.githubusercontent.com/74068143/242872308-2227eb35-75a8-4fba-9e68-a0e02bb8df64.png)

You can improve the image quality if you enable ExtBRC in CBR mode and set Scenario to GAME STREAMING. Also, the CPUEncTools parameter set to ON has a good effect on the image quality, but in the current version of the library there is a bug with the initialization of EncTools with the AV1 codec, so you need to leave it in the AUTO state. With AVC(H 264) and HEVC codecs, you can enable CPUEncTools.

**Comment by ckdt1105** [comment]
> @ma3uk

I will try to test the QSV parameters with your advice.
thank you.
