### ISSUE TITLE
Overflow seems to happen above 65535 kbps

### ISSUE THREAD

**Issue by ckdt1105** [ma3uk/obs-qsv-onevpl#9]
Encoder fails to start in CBR mode or (current bitrate - 65535)kbps

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/e759dd3c-fef1-4891-8689-fdbf91f086b3)
CBR 65540kbps = recoding error, encoding error while recoding.

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/93c1f5ea-1a95-451b-aeaa-b7f72a1bf7af)
(two 320kbps audio track is included)
CBR 66000kbps  = 465ish bitrate

![image](https://github.com/ma3uk/obs-qsv-onevpl/assets/74068143/cfa034bf-4c63-4453-8893-5310bd025668)
(two 320kbps audio track is included)
CBR 70000kbps  = 4465ish bitrate

**Comment by ckdt1105** [comment]
I have found that these bugs happen the same when using QSV in the vanilla version of OBS.

It looks like something is wrong with Intel's driver side.

(A380, 31.0.101.4369)

**Comment by ma3uk** [comment]
@ckdt1105 Unfortunately, the value of the TargetBitrate variable is limited to 16 bits inside the oneVPL library, so an overflow occurs. I have sent a request to Intel, waiting for a response in the hope of making changes to the library.

**Comment by ma3uk** [comment]
@ckdt1105 the solution has been found, I will post a new build in the near future

**Comment by ma3uk** [comment]
@ckdt1105 Fixed in release 1.1.0.0_dev4

**Comment by ckdt1105** [comment]
@ma3uk thank you
